# Sample yaml template ########################################################
default_language_version: system
default_stages: [commit, push]
exclude: "^$"
fail_fast: false
repos:
  - repo: git@github.com:hootsuite/pre-commit-php.git
    sha: master
    hooks:
      - id: php-lint
      - id: php-unit
      - id: php-cs-fixer
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: master
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-json
      - id: check-xml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
