# Travis CI provides several PHP versions, all of which include XDebug and PHPUnit. Travis CI uses phpenv to manage the different PHP versions installed on the virtual machines.

# Project language
dist: trusty
sudo: false
language: php
php:
  - '7.3'

matrix:
  allow_failures:
    - php:
        - '7.3'
  fast_finish: false

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# Install composer dependencies,
install:
  - rm composer.lock
  - travis_retry composer update --prefer-dist

# Commands you want to run that will verify your build.
script:
  - ./vendor/bin/phpunit --configuration phpunit.xml.dist

after_success:
  # Upload coverage data to codecov
  - codecov

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  on:
    branch: dev-ci
