# Project language
language: php

# Versions of PHP you want your project run with.
php:
 - 7.2
 - hhvm

# Commands to be run before your environment runs.
before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

# Install composer dependencies,
# Create database, schema and fixtures
install:
 - composer install
 - cp app/config/parameters.yml.dist app/config/parameters.yml
 - php bin/console doctrine:database:create --env=test
 - php bin/console doctrine:schema:create --env=test
 - php bin/console doctrine:fixtures:load -n --env=test

matrix:
 allow_failures:
   - php: 7.2
   - php: hhvm
 fast_finish: false

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
 - mysql

# Cache composer packages so "composer install" is faster
cache:
 directories:
   - $HOME/.composer/cache/files

# Commands you want to run that will verify your build.
script:
 - phpunit --coverage-text

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.

after_success:
  # Upload coverage data to codecov
  - codecov

# After a build, send email notification with the build results
notifications:
   on_success: never
   on_failure: always
  # irc:
  #   channels: "irc.freenode.org#xxxxx"
  #   template:
  #     - "%{repository_name}@%{branch}: %{message} (%{build_url})"
  #   on_success: change
  #   on_failure: change
  email: skeptycal@gmail.com
